# Generated by Django 3.2.9 on 2023-01-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(choices=[(1, 'Distance Base Price'), (2, 'Distance Additional Price')], default=1)),
                ('distance_in_meters', models.IntegerField(default=0)),
                ('price', models.FloatField(blank=True, null=True)),
                ('tmf_under_hour', models.FloatField(default=1)),
                ('tmf_for_two_hour', models.FloatField(default=1.25)),
                ('tmf_for_three_hour', models.FloatField(default=2.2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
